name: crimebook
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.6
  cupertino_icons: ^1.0.8
  firebase_core: ^3.4.1
  firebase_auth: ^5.2.1
  firebase_core_web: ^2.18.0
  provider: ^6.1.2
  cloud_firestore: ^5.4.2
  google_sign_in: ^6.2.1
  shimmer: ^3.0.0
  geolocator: ^13.0.1
  curved_navigation_bar: ^1.0.6
  flutter_spinkit: ^5.2.1
  syncfusion_flutter_charts: ^27.1.51
  google_fonts: ^6.2.1
  firebase_storage: ^12.3.3
  image_picker: ^1.1.2
  pdf: ^3.11.1
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  http: ^1.2.2
  url_launcher: ^6.3.1
  share_plus: ^10.0.3
  cached_network_image: ^3.4.1
  flutter_local_notifications: ^17.2.3
  intl: ^0.19.0
  timezone: ^0.9.4
  geocoding: ^3.0.0
  mailer: ^6.2.0
  country_state_city: ^0.1.6
  flutter_keyboard_visibility: ^6.0.0
  flutter_dotenv: ^5.2.1
  flutter_gemini: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
